### ISSUE TITLE
Loop text hard to read on dark background

### ISSUE THREAD

**Issue by CoenraadS** [vstirbu/vscode-mermaid-preview#49] opened 2018-05-08 07:14 UTC
### Expected behaviour

[Every Minute] should use a light font

```mermaid
sequenceDiagram
    participant One
    participant Two
    loop Every minute
    One ->> Two: Hello
    end
```

### Actual behaviour

![image](https://user-images.githubusercontent.com/5593825/39743088-1d8dbc8e-52a0-11e8-8eda-7a56a47105ec.png)

Include:
   * Screenshot
   * Preview mode: Mermaid
   * Theme used: dark

**Comment by vstirbu** [comment] 2018-05-08 07:26
duplicate of #41. please follow progress there.

**Closed by vstirbu** 2018-05-08 07:26 UTC
